routes/web.php
<?php

Route::group(['middleware' => ['web', 'auth', 'cekuser:1']], function() {

	/* --- Home --- */
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index')->name('home');
	
	/* --- Kategori --- */
	Route::get('kategori/data', 'KategoriController@listData')->name('kategori.data');
	Route::resource('kategori', 'KategoriController');
	
	/* --- Produk --- */
	Route::get('produk/data', 'ProdukController@listData')->name('produk.data');
	Route::post('produk/hapus', 'ProdukController@deleteSelected');
	Route::post('produk/cetak', 'ProdukController@printBarcode');
	Route::get('produk/pdf', 'ProdukController@makePDF');
	Route::post('produkstore', 'ProdukController@store');
	Route::resource('produk', 'ProdukController');

	/* --- Supplier --- */
	Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
	Route::resource('supplier', 'SupplierController');

	/* --- Member --- */
	Route::get('member/data', 'MemberController@listData')->name('member.data');
	Route::post('member/cetak', 'MemberController@printCard');
	Route::resource('member', 'MemberController');

	/* --- Pengeluaran --- */
	Route::get('pengeluaran/data', 'PengeluaranController@listData')->name('pengeluaran.data');
	Route::resource('pengeluaran', 'PengeluaranController');

	/* --- User --- */
	Route::get('user/data', 'UserController@listData')->name('user.data');
	Route::resource('user', 'UserController')->except([
		'show'
	]);	

	/* --- Pembelian --- */
	Route::get('pembelian/data', 'PembelianController@listData')->name('pembelian.data');
	Route::get('pembelian/{id}/tambah', 'PembelianController@create');
	Route::get('pembelian/{id}/lihat', 'PembelianController@show');
	Route::resource('pembelian', 'PembelianController')->except([
		'create'
	]);

	/* --- Pembelian Detail --- */
	Route::get('pembelian_detail/{id}/data', 'PembelianDetailController@listData')->name('pembelian_detail.data');
	Route::get('pembelian_detail/loadform/{diskon}/{total}', 'PembelianDetailController@loadForm');
	Route::resource('pembelian_detail', 'PembelianDetailController')->except([
		'create', 'show', 'edit'
	]);

	/* --- Penjualan --- */
	Route::get('penjualan/data', 'PenjualanController@listData')->name('penjualan.data');
	Route::get('penjualan/{id}/lihat', 'PenjualanController@show');
	Route::resource('penjualan', 'PenjualanController')->except([
		'create', 'edit', 'update'
	]);

	/* --- Laporan --- */
	Route::get('laporan', 'LaporanController@index')->name('laporan.index');
	Route::post('laporan', 'LaporanController@refresh')->name('laporan.refresh');
	Route::get('laporan/data/{awal}/{akhir}', 'LaporanController@listData')->name('laporan.data');
	Route::get('laporan/pdf/{awal}/{akhir}', 'LaporanController@exportPDF');

	/* --- Setting --- */
	Route::resource('setting', 'SettingController')->except([
		'show', 'create', 'destroy'
	]);

	/* --- Penjualan Detail --- */
	Route::get('transaksi/baru', 'PenjualanDetailController@newSession')->name('transaksi.new');
	Route::get('transaksi/{id}/data', 'PenjualanDetailController@listData')->name('transaksi.data');
	Route::get('transaksi/cetaknota', 'PenjualanDetailController@printNota')->name('transaksi.cetak');
	Route::get('transaksi/cetaknota/kecil', 'PenjualanDetailController@printNotaKecil')->name('transaksi.notakecil');
	Route::get('transaksi/notapdf', 'PenjualanDetailController@notaPDF')->name('transaksi.pdf');
	Route::post('transaksi/simpan', 'PenjualanDetailController@saveData')->name('transaksi.simpan');
	Route::get('transaksi/loadform/{diskon}/{total}/{diterima}', 'PenjualanDetailController@loadForm');
	Route::resource('transaksi', 'PenjualanDetailController')->except('show');
});

Route::group(['middleware' => ['web', 'auth']], function() {
	Route::get('user/profil', 'UserController@profil')->name('user.profil');
	Route::patch('user/{id}/change', 'UserController@changeProfil')->name('profil.update');

	/* --- Penjualan Detail --- */
	Route::get('transaksi/baru', 'PenjualanDetailController@newSession')->name('transaksi.new');
	Route::get('transaksi/{id}/data', 'PenjualanDetailController@listData')->name('transaksi.data');
	Route::get('transaksi/cetaknota', 'PenjualanDetailController@printNota')->name('transaksi.cetak');
	Route::get('transaksi/cetaknota/kecil', 'PenjualanDetailController@printNotaKecil')->name('transaksi.notakecil');
	Route::get('transaksi/notapdf', 'PenjualanDetailController@notaPDF')->name('transaksi.pdf');
	Route::post('transaksi/simpan', 'PenjualanDetailController@saveData')->name('transaksi.simpan');
	Route::get('transaksi/loadform/{diskon}/{total}/{diterima}', 'PenjualanDetailController@loadForm');
	Route::resource('transaksi', 'PenjualanDetailController')->except('show');
});

Route::get('/', 'HomeController@index')->name('home');
Auth::routes();

app/PenjualanDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PenjualanDetail extends Model
{
    protected $table = 'penjualan_detail';
    protected $primaryKey = 'id_penjualan_detail';

    public function produk()
    {
        return $this->belongsTo(Produk::class, 'id_produk');
    }

    public function penjualan()
    {
        return $this->belongsTo(Penjualan::class, 'id_penjualan');
    }
}

app/Http/Controllers/PenjualanDetailController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Redirect;
use PDF;
use App\Penjualan;
use App\Produk;
use App\Member;
use App\Setting;
use App\PenjualanDetail;

class PenjualanDetailController extends Controller
{
    public function index()
    {
    	$produk = Produk::all();
    	$member = Member::all();
    	$setting = Setting::all();

    	// Cek apakah ada transaksi yang sedang berjalan
        if(session('idpenjualan')) {
            $idpenjualan = session('idpenjualan');
            return view('penjualan_detail.index', compact('produk', 'member', 'setting', 'idpenjualan'));
    	} else {
            if (auth()->user()->level == 1) return redirect()->route('transaksi.new');
            else return redirect()->route('home');
        }
    }

    public function listData($id)
    {
    	$detail = PenjualanDetail::with('produk')->where('id_penjualan', '=', $id)->get();
		
		$no         = 0;
		$data       = array();
		$total      = 0;
		$total_item = 0;

		foreach ($detail as $list) {
    		$no++;
    		$row = array();
    		$row[] = $no;
    		$row[] = $list->produk['kode_produk'];
    		$row[] = $list->produk['nama_produk'];
    		$row[] = 'Rp. '. format_uang($list->harga_jual);
    		$row[] = '
				<input type="number" class="form-control input-sm" name="jumlah'. $list->id_penjualan_detail .'" value="'. $list->jumlah .'" onChange="changeCount('.$list->id_penjualan_detail.','.$list->stok.')" id="count">
            ';
            $row[] = $list->diskon .'%';
            $row[] = 'Rp. '. format_uang($list->sub_total);
            $row[] = '
                    <a onclick="deleteItem('. $list->id_penjualan_detail .')" class="btn btn-xs btn-flat btn-danger"><i class="fa fa-trash"></i> Hapus</a>
            ';
            $data[] = $row;

            $total += $list->harga_jual * $list->jumlah;
            $total_item += $list->jumlah;
    	}
    	$data[] = [
            '<span class="total hide">'.$total.'</span> <span class="totalitem hide">'.$total_item.'</span>',
            '',
            '',
            '',
            '',
            '',
            '',
            ''
        ];

        $output = ['data' => $data];
        return response()->json($output);
    }

    public function store(Request $request)
    {
    	$produk = Produk::where('id_produk', '=', $request['id_produk'])->first();
    	$detail = new PenjualanDetail;
    	$detail->id_penjualan = $request['idpenjualan'];
    	$detail->id_produk = $request['id_produk'];
    	$detail->harga_jual = $produk->harga_jual;
    	$detail->jumlah = 1;
    	$detail->diskon = $produk->diskon;

    	// sub total disesuaikan dengan diskon
    	$detail->sub_total = $produk->harga_jual - ($produk->diskon/100 * $produk->harga_jual);
    	$detail->save();
    }

    public function update(Request $request, $id)
    {
    	$nama_input = 'jumlah'. $id;
    	$detail = PenjualanDetail::find($id);
    	$total_harga = $request[$nama_input] * $detail->harga_jual;
    	
    	$detail->jumlah = $request[$nama_input];
    	$detail->sub_total = $total_harga - ($detail->diskon/100 * $total_harga);
    	$detail->update();
    }

    public function destroy($id)
    {
    	$detail = PenjualanDetail::find($id);
    	$detail->delete();
    }

    public function newSession()
    {
    	$penjualan = new Penjualan;
    	$penjualan->id_member = null;
    	$penjualan->total_item = 0;
    	$penjualan->total_harga = 0;
    	$penjualan->diskon = 0;
    	$penjualan->bayar = 0;
    	$penjualan->diterima = 0;
    	$penjualan->id_user = \Auth::user()->id;
    	$penjualan->save();

    	session(['idpenjualan' => $penjualan->id_penjualan]);
    	return Redirect::route('transaksi.index');
    }

    public function saveData(Request $request)
    {
    	$penjualan = Penjualan::find($request['idpenjualan']);
    	$penjualan->id_member = ($request['id_member'] != 0 ? $request['id_member'] : null);
    	$penjualan->total_item = $request['totalitem'];
    	$penjualan->total_harga = $request['total'];
    	$penjualan->diskon = $request['diskon'];
    	$penjualan->bayar = $request['bayar'];
    	$penjualan->diterima = $request['diterima'];
    	$penjualan->update();

    	// Update atok data sesuai data yang dibeli
    	$detail = PenjualanDetail::where('id_penjualan', '=', $request['idpenjualan'])->get();
    	foreach ($detail as $data) {
    		$produk = Produk::where('id_produk', '=', $data->id_produk)->first();
    		$produk->stok -= $data->jumlah;
    		$produk->update();
    	}
    	return redirect(route('transaksi.cetak'));
    }

    public function loadForm($diskon = 0, $total, $diterima)
    {
    	$bayar = $total - ($diskon / 100 * $total);
    	$kembali = ($diterima != 0) ? $diterima - $bayar : 0;
    	$data = [
    		'totalrp' => format_uang($total),
    		'bayar' => $bayar,
    		'bayarrp' => format_uang($bayar),
    		'terbilang' => ucwords(terbilang($bayar)). ' Rupiah',
    		'kembalirp' => format_uang($kembali),
    		'kembaliterbilang' => ucwords(terbilang($kembali)). ' Rupiah'
    	];

    	return response()->json($data);
    }

    public function printNota()
    {
        $setting = Setting::first();

        return view('penjualan_detail.selesai', compact('setting'));
    }

    public function printNotaKecil()
    {
        $setting = Setting::first();
        $detail = PenjualanDetail::with('produk')
                ->where('id_penjualan', '=', session('idpenjualan'))
                ->get();
                
        $penjualan = Penjualan::find(session('idpenjualan'));
        $no = 0;

        return view('penjualan_detail.notakecil', compact('setting', 'detail', 'penjualan', 'no'));
    }

    public function notaPDF()
    {
    	$detail = PenjualanDetail::with('produk')
    			->where('id_penjualan', '=', session('idpenjualan'))
    			->get();
    			
    	$penjualan = Penjualan::find(session('idpenjualan'));
    	$setting = Setting::first();
    	$no = 0;

    	$pdf = PDF::loadView('penjualan_detail.notapdf', compact('detail', 'penjualan', 'setting', 'no'));
    	$pdf->setPaper(array(0,0,609,440), 'potrait');
    	return $pdf->stream();
    }
}

resources/views/penjualan_detail/index.blade.php
@extends('layouts.app')

@section('css')
<style>
	#tampil-bayar {
		font-size: 5em; 
		text-align: center; 
		height: 100px;
	}	

	#tampil-terbilang {
		padding: 10px; 
		background-color: #f0f0f0;
	}

	@media(max-width: 768px) {
		#tampil-bayar {
			font-size: 3em;
			white-space: nowrap;
			height: 70px;
			padding-top: 5px;
			overflow: auto;
		}
	}
</style>
@endsection

@section('title')
	Transaksi Penjualan
@endsection

@section('breadcrumb')
	@parent
	<li>Penjualan</li>
	<li>Tambah</li>
@endsection

@section('content')
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
			    <div class="box-body">
			        <form class="fom-horizontal form-produk" method="post">
						@csrf {{ method_field('POST') }}
						<input type="hidden" name="idpenjualan" value="{{ $idpenjualan }}">

						<div class="form-group row">
							<label for="kode" class="col-md-2 control-label">Kode Produk</label>
							<div class="col-md-5">
								<div class="input-group">
									<input type="hidden" name="id_produk" id="id_produk">
									<input type="text" name="kode" id="kode" class="form-control" onkeypress="showProduct()">
									<span class="input-group-btn">
										<button onclick="showProduct()" type="button" class="btn btn-info btn-flat"><i class="fa fa-search"></i> </button>
									</span>
								</div>
							</div>
						</div>
					</form>

					<form class="form-keranjang table-responsive" method="post">
						@csrf @method('PATCH')
						<table class="table table-striped table-bordered tabel-penjualan">
						    <thead>
						    	<th width="20">No</th>
						        <th>Kode Produk</th>
						        <th>Nama Produk</th>
						        <th align="right">Harga</th>
						        <th>Jumlah</th>
						        <th>Diskon</th>
						        <th align="right">Sub Total</th>
						        <th width="100">Aksi</th>
						    </thead>
						    <tbody></tbody>
						</table> <br>
						
						<style>
							.tabel-penjualan tbody tr:last-child {
								display: none;
							}
						</style>
					</form>

					<div class="col-md-8" style="padding: 0; margin: 0;">
						<div id="tampil-bayar" class="bg-primary"></div>
						<div id="tampil-terbilang"></div>
					</div>

					<div class="col-md-4">
						<form class="fom-horizontal form-penjualan" method="post" action="{{ route('transaksi.simpan') }}">
							@csrf @method('POST')
							<input type="hidden" name="idpenjualan" value="{{ $idpenjualan }}">
							<input type="hidden" name="total" id="total">
							<input type="hidden" name="totalitem" id="totalitem">
							<input type="hidden" name="bayar" id="bayar">

							<div class="form-group row">
								<label for="totalrp" class="col-md-4 control-label">Total</label>
								<div class="col-md-8">
									<input type="text" name="totalrp" id="totalrp" class="form-control" readonly>
								</div>
							</div>

							<div class="form-group row">
								<label for="member" class="col-md-4 control-label">Member</label>
								<div class="col-md-8">
									<div class="input-group">
										<input type="hidden" name="id_member" id="id_member">
										<input type="text" name="member" id="member" class="form-control" value="0">
										<span class="input-group-btn"><button onclick="showMember()" type="button" class="btn btn-info btn-flat"><i class="fa fa-arrow-right"></i></button></span>
									</div>
								</div>
							</div>

							<div class="form-group row">
								<label for="diskon" class="col-md-4 control-label">Diskon</label>
								<div class="col-md-8">
									<input type="text" name="diskon" id="diskon" class="form-control" value="0" readonly>
								</div>
							</div>

							<div class="form-group row">
								<label for="bayarrp" class="col-md-4 control-label">Bayar</label>
								<div class="col-md-8">
									<input type="text" name="bayarrp" id="bayarrp" class="form-control" readonly>
								</div>
							</div>

							<div class="form-group row">
								<label for="diterima" class="col-md-4 control-label">Diterima</label>
								<div class="col-md-8">
									<input type="number" name="diterima" id="diterima" class="form-control">
								</div>
							</div>

							<div class="form-group row">
								<label for="kembali" class="col-md-4 control-label">Kembali</label>
								<div class="col-md-8">
									<input type="text" class="form-control" id="kembali" value="0" readonly>
								</div>
							</div>
						</form>
					</div>
			    </div>

			    <div class="box-footer">
					<button type="submit" class="btn btn-primary btn-sm btn-flat pull-right simpan"><i class="fa fa-floppy-o"></i> Simpan Transaksi</button>
				</div>
			</div>
		</div>
	</div>
	@include('penjualan_detail.produk')
	@include('penjualan_detail.member')
@endsection

@section('script')
	<script>
		var table;
		
		$(function() {
			$('.tabel-produk').DataTable();
			table = $('.tabel-penjualan').DataTable({
				'dom' : 'Brt',
				'bSort' : false,
				'serverSide' : true,
				'autoWidth' : false,
				'ajax' : {
					'url' : '{{ route('transaksi.data', $idpenjualan) }}',
					'type' : 'GET'
				}
			}).on('draw.dt', function() {
				loadForm($('#diskon').val());
			})
		})

		$('body').addClass('sidebar-collapse')
		$('.form-produk, .form-keranjang').on('submit', function() {
			return false;
		})

		$('#kode').change(function() {
			addItem();
		})

		$('#member').change(function() {
			selectMember($(this).val())
		})

		// Jalankan fungsi loadForm() ketika diterima diubah
		$('#diterima').change(function() {
			if ($(this).val() == '') $(this).val(0).select()
			loadForm($('#diskon').val(), $(this).val())
		}).focus(function() {
			$(this).select()
		})

		// menyimpan form transaksi
		$('.simpan').click(function() {
			$('.form-penjualan').submit();
		})

		function addItem() {
			$.ajax({
				url : '{{ route('transaksi.store') }}',
				type : 'POST',
				data : $('.form-produk').serialize(),
				success : function(data) {
					$('#kode').val('').focus();
					table.ajax.reload(function(){
						loadForm($('#diskon').val())
					})
				}, 
				error : function() {
					alert('Tidak dapat menyimpan data!');
				}
			})
		}

		function showProduct() {
			$('#modal-produk').modal('show');
		}

		function showMember() {
			$('#modal-member').modal('show');
		}

		function selectItem(id, kode) {
			$('#id_produk').val(id);
			$('#kode').val(kode);
			$('#modal-produk').modal('hide');
			addItem();
		}

		function changeCount(id, stok) {
			// if($('#count').val() > stok) {
			// 	alert('Stok tersisa '+ stok);
			// 	$('#count').val('')
			// }

			$.ajax({
				url  : 'transaksi/'+ id,
				type : 'POST',
				data : $('.form-keranjang').serialize(),
				success : function(data) {
					table.ajax.reload(function() {
						loadForm($('#diskon').val());
					})
				}, 
				error : function() {
					alert('Tidak dapat menyimpan data!');
				}
			})
		}

		function selectMember(id, kode) {
			$('#modal-member').modal('hide')
			$('#diskon').val('{{ $setting[0]->diskon_member }}')
			$('#id_member').val(id)
			$('#member').val(kode)
			loadForm($('#diskon')).val()
			$('#diterima').val(0).focus().select()
		}

		function deleteItem(id) {
			if(confirm('Apakah yakin data akan dihapus?')) {
				$.ajax({
					url : 'transaksi/'+ id,
					type : 'POST',
					data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
					success :  function(data) {
						table.ajax.reload(function() {
							loadForm($('#diskon'));
						})
					},
					error : function(data) {
						alert('Tidak dapat menghapus data!');
					}
				})
			}
		}

		function loadForm(diskon = 0, diterima = 0) {
			$('#total').val($('.total').text());
			$('#totalitem').val($('.totalitem').text());
			
			if(diskon) diskon = diskon;
			else diskon = 0;

			$.ajax({
				url : 'transaksi/loadform/' + diskon + '/' + $('#total').val() + '/' + diterima,
				type : 'GET',
				dataType : 'JSON',
				success : function(data) {
					$('#totalrp').val('Rp. '+ data.totalrp);
					$('#bayarrp').val('Rp. '+ data.bayarrp);
					$('#bayar').val(data.bayar);
					$('#tampil-bayar').text('Bayar: Rp. '+ data.bayarrp);
					$('#tampil-terbilang').text(data.terbilang);

					$('#kembali').val('Rp. '+ data.kembalirp);
					if($('#diterima').val() != 0) {
						$('#tampil-bayar').html('<small>Kembali:</small> Rp. '+ data.kembalirp)
						$('#tampil-terbilang').text(data.kembaliterbilang);
					}
				},
				error : function(data) {
					// alert('Tidak dapat menampilkan data!');
				}
			})
		}
	</script>
@endsection

resources/views/penjualan_detail/member.blade.php
<div class="modal fade" id="modal-member" tabindex="1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times; </span></button>
				<h4 class="modal-title">Cari Member</h4>
			</div>

			<div class="modal-body" style="overflow: auto;">
				<table class="table table-striped table-bordered tabel-member">
				    <thead>
				        <th>Kode Member</th>
				        <th>Nama Member</th>
				        <th>Alamat</th>
				        <th>Telpon</th>
				        <th>Aksi</th>
				    </thead>
				
				    <tbody>
				        @foreach($member as $data)
				        	<tr>
				        		<td>{{ $data->kode_member }}</td>
				        		<td>{{ $data->nama }}</td>
				        		<td>{{ $data->alamat }}</td>
				        		<td>{{ $data->telpon }}</td>
				        		<td>
				        			<a onclick="selectMember({{ $data->id_member }}, {{ $data->kode_member }})" class="btn btn-primary btn-sm btn-flat"><i class="fa fa-check-circle"></i> Pilih</a>
				        		</td>
				        	</tr>
				        @endforeach
				    </tbody>
				</table>
			</div>
		</div>
	</div>
</div>

resources/views/penjualan_detail/notakecil.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Nota Kecil</title>
	<style>
		* {
			font-family: 'consolas', sans-serif;
		}
		span {display: block; margin: 3px;}
		.clear {
			clear: both;
		}
		@media print {
			@page 
	        {
	            margin: 0mm;
	        }
		}
	</style>
</head>
<body style="width: 300px; margin: auto; padding: .5%;" onload="window.print()">
	
	<div style="text-align: center;">
		<h3 style="margin-bottom: 5px;">{{ strtoupper($setting->nama_perusahaan) }}</h3>
		<span>{{ $setting->alamat }}</span>
	</div>
	<br>
	<div>
		<span style="float: left;">{{ (date('Y-m-d')) }}</span>
		<span style="float: right; margin-right: .3em;">{{ Auth::user()->name }}</span>
	</div>
	<div class="clear"></div>
	<span>No : 000000{{ $penjualan->id_penjualan }}</span>

	<span>===============================</span><br>
	<table border="0" width="100%">
		@foreach($detail as $list)
		<tr>
			<td colspan="2">{{ $list->produk->nama_produk }}</td>
		</tr>
		<tr>
			<td>{{ $list->jumlah }} x {{ format_uang($list->harga_jual) }}</td> 
			<td></td> 
			<td align="right">{{ format_uang(($list->jumlah * $list->harga_jual)) }}</td>
		</tr>
		@endforeach
	</table>
	
	<span style="text-align: center;">- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -</span>
	<table border="0" width="100%">
		<tr>
			<td>Total Harga:</td> 
			<td align="right">{{ format_uang($penjualan->total_harga) }}</td>
		</tr>
		<tr>
			<td>Total Item:</td> 
			<td align="right">{{ format_uang($penjualan->total_item) }}</td>
		</tr>
		<tr>
			<td>Diskon Member:</td> 
			<td align="right">{{ format_uang($penjualan->diskon) }}%</td>
		</tr>
		<tr>
			<td>Total Bayar:</td> 
			<td align="right">{{ format_uang($penjualan->bayar) }}</td>
		</tr>
		<tr>
			<td>Diterima:</td> 
			<td align="right">{{ format_uang($penjualan->diterima) }}</td>
		</tr>
		<tr>
			<td>Kembali:</td> 
			<td align="right">{{ format_uang($penjualan->diterima - $penjualan->bayar) }}</td>
		</tr>
	</table>

	<span>===============================</span>
	<span style="text-align: center;">-- TERIMA KASIH --</span>

</body>
</html>

resources/views/penjualan_detail/notapdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Nota PDF</title>
	<style>
		table td {
			font-family: arial; 
			font-size: 14px;
		}
		table.data td,
		table.data th{
			border: 1px solid #ccc;
			padding: 5px;
		}
		table.data th {
			text-align: center;
		}
		table.data {border-collapse: collapse;}
	</style>
</head>
<body>

	<table width="100%">
		<tr>
			<td rowspan="4" width="60%">
				<img src="images/{{ $setting->logo }}" width="120"><br>
				{{ $setting->alamat }} <br><br>
			</td>
			<td>Tanggal</td>
			<td>: {{ tanggal_indonesia(date('Y-m-d')) }}</td>
		</tr>
		<tr>
			<td>Kode Member</td>
			<td>: {{ $penjualan->member['kode_member'] }}</td>
		</tr>
	</table>

	<table width="100%" class="data">
		<thead>
			<tr>
				<th>No</th>
				<th>Kode Produk</th>
				<th>Nama Produk</th>
				<th>Harga Satuan</th>
				<th>Jumlah</th>
				<th>Diskon</th>
				<th>Subtotal</th>
			</tr>
		</thead>
		<tbody>
		@foreach ($detail as $data)
			<tr>
				<td align="center">{{ ++$no }}</td>
				<td>{{ $data->produk['kode_produk'] }}</td>
				<td>{{ $data->produk['nama_produk'] }}</td>
				<td align="right">{{ $data->harga_jual }}</td>
				<td align="right">{{ $data->jumlah }}</td>
				<td align="right">{{ format_uang($data->diskon) }}%</td>
				<td align="right">{{ format_uang($data->sub_total) }}</td>
			</tr>
		@endforeach
		</tbody>
		<tfoot>
			<tr>
				<td colspan="6" align="right"><b>Total Harga</b></td>
				<td align="right"><b>{{ format_uang($penjualan->total_harga) }}</b></td>
			</tr>
			<tr>
				<td colspan="6" align="right"><b>Diskon</b></td>
				<td align="right"><b>{{ format_uang($penjualan->diskon) }}%</b></td>
			</tr>
			<tr>
				<td colspan="6" align="right"><b>Total Bayar</b></td>
				<td align="right"><b>{{ format_uang($penjualan->bayar) }}</b></td>
			</tr>
			<tr>
				<td colspan="6" align="right"><b>Diterima</b></td>
				<td align="right"><b>{{ format_uang($penjualan->diterima) }}</b></td>
			</tr>
			<tr>
				<td colspan="6" align="right"><b>Kembali</b></td>
				<td align="right"><b>{{ format_uang($penjualan->diterima - $penjualan->bayar) }}</b></td>
			</tr>
		</tfoot>
	</table>

	<table width="100%">
		<tr>
			<td><b>Terimakasih telah berbelanja dan sampai jumpa</b></td>
			<td align="center">Kasir <br><br> {{ Auth::user()->name }}</td>
		</tr>
	</table>
</body>
</html>