routes/web.php
<?php

Route::group(['middleware' => ['web', 'auth', 'cekuser:1']], function() {

	/* --- Home --- */
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index')->name('home');
	
	/* --- Kategori --- */
	Route::get('kategori/data', 'KategoriController@listData')->name('kategori.data');
	Route::resource('kategori', 'KategoriController');
	
	/* --- Produk --- */
	Route::get('produk/data', 'ProdukController@listData')->name('produk.data');
	Route::post('produk/hapus', 'ProdukController@deleteSelected');
	Route::post('produk/cetak', 'ProdukController@printBarcode');
	Route::get('produk/pdf', 'ProdukController@makePDF');
	Route::post('produkstore', 'ProdukController@store');
	Route::resource('produk', 'ProdukController');

	/* --- Supplier --- */
	Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
	Route::resource('supplier', 'SupplierController');

	/* --- Member --- */
	Route::get('member/data', 'MemberController@listData')->name('member.data');
	Route::post('member/cetak', 'MemberController@printCard');
	Route::resource('member', 'MemberController');

	/* --- Pengeluaran --- */
	Route::get('pengeluaran/data', 'PengeluaranController@listData')->name('pengeluaran.data');
	Route::resource('pengeluaran', 'PengeluaranController');

	/* --- User --- */
	Route::get('user/data', 'UserController@listData')->name('user.data');
	Route::resource('user', 'UserController')->except([
		'show'
	]);	

	/* --- Pembelian --- */
	Route::get('pembelian/data', 'PembelianController@listData')->name('pembelian.data');
	Route::get('pembelian/{id}/tambah', 'PembelianController@create');
	Route::get('pembelian/{id}/lihat', 'PembelianController@show');
	Route::resource('pembelian', 'PembelianController')->except([
		'create'
	]);

	/* --- Pembelian Detail --- */
	Route::get('pembelian_detail/{id}/data', 'PembelianDetailController@listData')->name('pembelian_detail.data');
	Route::get('pembelian_detail/loadform/{diskon}/{total}', 'PembelianDetailController@loadForm');
	Route::resource('pembelian_detail', 'PembelianDetailController')->except([
		'create', 'show', 'edit'
	]);

	/* --- Penjualan --- */
	Route::get('penjualan/data', 'PenjualanController@listData')->name('penjualan.data');
	Route::get('penjualan/{id}/lihat', 'PenjualanController@show');
	Route::resource('penjualan', 'PenjualanController')->except([
		'create', 'edit', 'update'
	]);

	/* --- Laporan --- */
	Route::get('laporan', 'LaporanController@index')->name('laporan.index');
	Route::post('laporan', 'LaporanController@refresh')->name('laporan.refresh');
	Route::get('laporan/data/{awal}/{akhir}', 'LaporanController@listData')->name('laporan.data');
	Route::get('laporan/pdf/{awal}/{akhir}', 'LaporanController@exportPDF');

	/* --- Setting --- */
	Route::resource('setting', 'SettingController')->except([
		'show', 'create', 'destroy'
	]);

	/* --- Penjualan Detail --- */
	Route::get('transaksi/baru', 'PenjualanDetailController@newSession')->name('transaksi.new');
	Route::get('transaksi/{id}/data', 'PenjualanDetailController@listData')->name('transaksi.data');
	Route::get('transaksi/cetaknota', 'PenjualanDetailController@printNota')->name('transaksi.cetak');
	Route::get('transaksi/cetaknota/kecil', 'PenjualanDetailController@printNotaKecil')->name('transaksi.notakecil');
	Route::get('transaksi/notapdf', 'PenjualanDetailController@notaPDF')->name('transaksi.pdf');
	Route::post('transaksi/simpan', 'PenjualanDetailController@saveData')->name('transaksi.simpan');
	Route::get('transaksi/loadform/{diskon}/{total}/{diterima}', 'PenjualanDetailController@loadForm');
	Route::resource('transaksi', 'PenjualanDetailController')->except('show');
});

Route::group(['middleware' => ['web', 'auth']], function() {
	Route::get('user/profil', 'UserController@profil')->name('user.profil');
	Route::patch('user/{id}/change', 'UserController@changeProfil')->name('profil.update');

	/* --- Penjualan Detail --- */
	Route::get('transaksi/baru', 'PenjualanDetailController@newSession')->name('transaksi.new');
	Route::get('transaksi/{id}/data', 'PenjualanDetailController@listData')->name('transaksi.data');
	Route::get('transaksi/cetaknota', 'PenjualanDetailController@printNota')->name('transaksi.cetak');
	Route::get('transaksi/cetaknota/kecil', 'PenjualanDetailController@printNotaKecil')->name('transaksi.notakecil');
	Route::get('transaksi/notapdf', 'PenjualanDetailController@notaPDF')->name('transaksi.pdf');
	Route::post('transaksi/simpan', 'PenjualanDetailController@saveData')->name('transaksi.simpan');
	Route::get('transaksi/loadform/{diskon}/{total}/{diterima}', 'PenjualanDetailController@loadForm');
	Route::resource('transaksi', 'PenjualanDetailController')->except('show');
});

Route::get('/', 'HomeController@index')->name('home');
Auth::routes();

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    protected $table = 'supplier';
    protected $primaryKey = 'id_supplier';

    public function pembelian() {
    	return $this->hasMany(Pembelian::class, 'id_supplier');
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Supplier;

class SupplierController extends Controller
{
    public function index() 
    {
    	return view('supplier.index');
    }

    public function listData()
    {
    	$supplier = Supplier::orderBy('id_supplier', 'desc')->get();
        $no = 0;
        $data = array();

        foreach ($supplier as $list) {
            $no++;
            $row = array();
            $row[] = $no;
            $row[] = $list->nama;
            $row[] = $list->alamat;
            $row[] = $list->telpon;
            $row[] = '
                    <a onclick="editForm('. $list->id_supplier .')" class="btn btn-xs btn-flat btn-info"><i class="fa fa-pencil"></i> Edit</a>
                    <a onclick="deleteData('. $list->id_supplier .')" class="btn btn-xs btn-flat btn-danger"><i class="fa fa-trash"></i> Hapus</a>
            ';
            $data[] = $row;
        }

        $output = ['data' => $data];
        return response()->json($output);
    }

    public function store(Request $request)
    {
        $supplier = new Supplier;
        $supplier->nama = $request['nama'];
        $supplier->alamat = $request['alamat'];
        $supplier->telpon = $request['telpon'];
        $supplier->save();
    }

    
    public function edit($id)
    {
        $supplier = Supplier::find($id);
        echo json_encode($supplier);
    }

    
    public function update(Request $request, $id)
    {
        $supplier = supplier::find($id);
        $supplier->nama = $request['nama'];
        $supplier->alamat = $request['alamat'];
        $supplier->telpon = $request['telpon'];
        $supplier->update();
    }

    
    public function destroy($id)
    {
        $supplier = supplier::find($id);
        $supplier->delete();
    }
}

resources/views/supplier/form.blade.php
<div class="modal fade" id="modal-form" tabindex="1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form class="fom-horizontal" method="post" data-toggle="validator">
				@csrf {{ method_field('POST') }}
				
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times; </span></button>
					<h4 class="modal-title"></h4>
				</div>

				<div class="modal-body">
					<input type="hidden" id="id" name="id">

					<div class="form-group row">
						<label for="nama" class="col-md-2 col-md-offset-1 control-label">Nama Supplier</label>
						<div class="col-md-6">
							<input type="text" name="nama" id="nama" class="form-control" required autofocus>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group row">
						<label for="alamat" class="col-md-2 col-md-offset-1 control-label">Alamat</label>
						<div class="col-md-6">
							<input type="text" name="alamat" id="alamat" class="form-control" required autofocus>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group row">
						<label for="telpon" class="col-md-2 col-md-offset-1 control-label">Telpon</label>
						<div class="col-md-6">
							<input type="text" name="telpon" id="telpon" class="form-control" required autofocus>
							<span class="help-block with-errors"></span>
						</div>
					</div>
				</div>

				<div class="modal-footer">
					<button type="submit" class="btn btn-sm btn-flat btn-primary btn-save"><i class="fa fa-floppy-o"></i>  Simpan</button>
					<button type="button" class="btn btn-sm btn-flat btn-warning" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> Batal</button>
				</div>
			</form>
		</div>
	</div>
</div>

resources/views/supplier/index.blade.php
@extends('layouts.app')

@section('title')
	Daftar Supplier
@endsection

@section('breadcrumb')
	@parent
	<li>Supplier</li>
@endsection

@section('content')
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
			    <div class="box-header with-border">
			        <a onclick="addForm()" class="btn btn-success btn-xs btn-flat"><i class="fa fa-plus-circle"></i> Tambah</a>
			    </div>
			
			    <div class="box-body" style="overflow: auto;">
			        <table class="table table-striped table-bordered">
			            <thead>
			                <th width="30">No</th>
			                <th>Nama Supplier</th>
			                <th>Alamat</th>
			                <th>Telpon</th>
			                <th width="100">Aksi</th>
			            </thead>
			            <tbody></tbody>
			        </table>
			    </div>
			</div>
		</div>
	</div>
	@include('supplier.form')
@endsection

@section('script')
	<script>
		var table, save_method;
	$(function() {
		table = $('.table').DataTable({
			'processing' : true,
			'autoWidth' : false,
			'ajax' : {
				'url' : '{{ route('supplier.data') }}',
				'type' : 'GET'
			}
		});
	})

		$(function() {
			$('#modal-form').validator().on('submit', function(e) {
				if(!e.preventDefault()) {
					var id = $('#id').val();
					
					if(save_method == 'add') url = '{{ route("supplier.store") }}';
					else url = 'supplier/' + id;

					$.ajax({
						url : url,
						type : 'POST',
						data : $('#modal-form form').serialize(),
						success : function(data) {
							$('#modal-form').modal('hide');
							table.ajax.reload();
						}
					})

					return false;
				}
			})
		})

		function addForm() {
			save_method = 'add';
			$('#modal-form').modal('show');
			$('input[name=_method]').val('POST');
			$('#modal-form form')[0].reset();
			$('.modal-title').text('Tambah Supplier');
			$('#modal-form form #nama').focus();
		}

		function editForm(id) {
			save_method = 'edit';
			$('input[name=_method]').val('PATCH');
			$('#modal-form form')[0].reset();

			$.ajax({
				url : 'supplier/' + id + '/edit',
				type : 'GET',
				dataType : 'JSON',
				success : function(data) {
					$('#modal-form').modal('show');
					$('.modal-title').text('Edit Supplier');

					$('#id').val(data.id_supplier);
					$('#nama').val(data.nama);
					$('#alamat').val(data.alamat);
					$('#telpon').val(data.telpon);
				}, 
				error : function() {
					alert('Tidak dapat menampilkan data');
				}
			})
		}

		function deleteData(id) {
			if(confirm('Apakah yakin data akan dihapus?')) {
				$.ajax({
					url : 'supplier/' + id,
					type : 'POST',
					data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
					success : function(data) {
						table.ajax.reload();
					},
					error : function() {
						alert('Tidak dapat menghapus data!');
					}
				})
			}
		}
	</script>
@endsection