routes/web.php
<?php

Route::group(['middleware' => ['web', 'auth', 'cekuser:1']], function() {

	/* --- Home --- */
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index')->name('home');
	
	/* --- Kategori --- */
	Route::get('kategori/data', 'KategoriController@listData')->name('kategori.data');
	Route::resource('kategori', 'KategoriController');
	
	/* --- Produk --- */
	Route::get('produk/data', 'ProdukController@listData')->name('produk.data');
	Route::post('produk/hapus', 'ProdukController@deleteSelected');
	Route::post('produk/cetak', 'ProdukController@printBarcode');
	Route::get('produk/pdf', 'ProdukController@makePDF');
	Route::post('produkstore', 'ProdukController@store');
	Route::resource('produk', 'ProdukController');

	/* --- Supplier --- */
	Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
	Route::resource('supplier', 'SupplierController');

	/* --- Member --- */
	Route::get('member/data', 'MemberController@listData')->name('member.data');
	Route::post('member/cetak', 'MemberController@printCard');
	Route::resource('member', 'MemberController');

	/* --- Pengeluaran --- */
	Route::get('pengeluaran/data', 'PengeluaranController@listData')->name('pengeluaran.data');
	Route::resource('pengeluaran', 'PengeluaranController');

	/* --- User --- */
	Route::get('user/data', 'UserController@listData')->name('user.data');
	Route::resource('user', 'UserController')->except([
		'show'
	]);	

	/* --- Pembelian --- */
	Route::get('pembelian/data', 'PembelianController@listData')->name('pembelian.data');
	Route::get('pembelian/{id}/tambah', 'PembelianController@create');
	Route::get('pembelian/{id}/lihat', 'PembelianController@show');
	Route::resource('pembelian', 'PembelianController')->except([
		'create'
	]);

	/* --- Pembelian Detail --- */
	Route::get('pembelian_detail/{id}/data', 'PembelianDetailController@listData')->name('pembelian_detail.data');
	Route::get('pembelian_detail/loadform/{diskon}/{total}', 'PembelianDetailController@loadForm');
	Route::resource('pembelian_detail', 'PembelianDetailController')->except([
		'create', 'show', 'edit'
	]);

	/* --- Penjualan --- */
	Route::get('penjualan/data', 'PenjualanController@listData')->name('penjualan.data');
	Route::get('penjualan/{id}/lihat', 'PenjualanController@show');
	Route::resource('penjualan', 'PenjualanController')->except([
		'create', 'edit', 'update'
	]);

	/* --- Laporan --- */
	Route::get('laporan', 'LaporanController@index')->name('laporan.index');
	Route::post('laporan', 'LaporanController@refresh')->name('laporan.refresh');
	Route::get('laporan/data/{awal}/{akhir}', 'LaporanController@listData')->name('laporan.data');
	Route::get('laporan/pdf/{awal}/{akhir}', 'LaporanController@exportPDF');

	/* --- Setting --- */
	Route::resource('setting', 'SettingController')->except([
		'show', 'create', 'destroy'
	]);

	/* --- Penjualan Detail --- */
	Route::get('transaksi/baru', 'PenjualanDetailController@newSession')->name('transaksi.new');
	Route::get('transaksi/{id}/data', 'PenjualanDetailController@listData')->name('transaksi.data');
	Route::get('transaksi/cetaknota', 'PenjualanDetailController@printNota')->name('transaksi.cetak');
	Route::get('transaksi/cetaknota/kecil', 'PenjualanDetailController@printNotaKecil')->name('transaksi.notakecil');
	Route::get('transaksi/notapdf', 'PenjualanDetailController@notaPDF')->name('transaksi.pdf');
	Route::post('transaksi/simpan', 'PenjualanDetailController@saveData')->name('transaksi.simpan');
	Route::get('transaksi/loadform/{diskon}/{total}/{diterima}', 'PenjualanDetailController@loadForm');
	Route::resource('transaksi', 'PenjualanDetailController')->except('show');
});

Route::group(['middleware' => ['web', 'auth']], function() {
	Route::get('user/profil', 'UserController@profil')->name('user.profil');
	Route::patch('user/{id}/change', 'UserController@changeProfil')->name('profil.update');

	/* --- Penjualan Detail --- */
	Route::get('transaksi/baru', 'PenjualanDetailController@newSession')->name('transaksi.new');
	Route::get('transaksi/{id}/data', 'PenjualanDetailController@listData')->name('transaksi.data');
	Route::get('transaksi/cetaknota', 'PenjualanDetailController@printNota')->name('transaksi.cetak');
	Route::get('transaksi/cetaknota/kecil', 'PenjualanDetailController@printNotaKecil')->name('transaksi.notakecil');
	Route::get('transaksi/notapdf', 'PenjualanDetailController@notaPDF')->name('transaksi.pdf');
	Route::post('transaksi/simpan', 'PenjualanDetailController@saveData')->name('transaksi.simpan');
	Route::get('transaksi/loadform/{diskon}/{total}/{diterima}', 'PenjualanDetailController@loadForm');
	Route::resource('transaksi', 'PenjualanDetailController')->except('show');
});

Route::get('/', 'HomeController@index')->name('home');
Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Hash;
use Auth;

class UserController extends Controller
{
    public function index()
    {
        return view('user.index');
    }

    
    public function listData() 
    {
        $user = User::where('level', '!=', 1)->orderBy('id', 'desc')->get();
        $no = 0;
        $data = array();

        foreach ($user as $list) {
            $no++;
            $row = array();
            $row[] = $no;
            $row[] = $list->name;
            $row[] = $list->email;
            $row[] = '
                    <a onclick="editForm('. $list->id .')" class="btn btn-xs btn-flat btn-info"><i class="fa fa-pencil"></i> Edit</a>
                    <a onclick="deleteData('. $list->id .')" class="btn btn-xs btn-flat btn-danger"><i class="fa fa-trash"></i> Hapus</a>
            ';
            $data[] = $row;
        }

        $output = ['data' => $data];
        return response()->json($output);
    }

    
    public function store(Request $request)
    {
        $user = new User;
        $user->name = $request['nama'];
        $user->email = $request['email'];
        $user->password = bcrypt($request['password']);
        $user->level = 2;
        $user->foto = 'user.png';
        $user->save();
    }

    
    public function edit($id)
    {
        $user = User::find($id);
        echo json_encode($user);
    }

    
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->name = $request['nama'];
        $user->email = $request['email'];
        if(!empty($request['password'])) $user->password = bcrypt($request['password']);
        $user->update();
    }

    
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
    }


    public function profil() 
    {
    	$user = Auth::user();
    	return view('user.profil', compact('user'));
    }


    public function changeProfil(Request $request, $id) 
    {
    	$msg = 'success';
    	$user = User::find($id);

        $user->name = $request['nama'];
    	if(!empty($request['password'])) {
    		if(Hash::check($request['passwordlama'], $user->password)) {
    			$user->password = bcrypt($request['password']);
    		}
    	}

    	if($request->hasFile('foto')) {
    		$file = $request->file('foto');
    		$nama_gambar = 'fotouser '. $id .'.'. $file->getClientOriginalExtension();
    		$lokasi = public_path('images');

    		$file->move($lokasi, $nama_gambar);
    		$user->foto = $nama_gambar;
    		$datagambar = $nama_gambar;
    	} else {
            $datagambar = $user->foto;
        }
		
        $user->update();
		echo json_encode([
            'msg' => $msg, 
            'url' => asset('public/images/'. $datagambar),
            'name' => $user->name
        ]);
    }
}

resources/views/user/form.blade.php
<div class="modal fade" id="modal-form" tabindex="1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form class="fom-horizontal" method="post" data-toggle="validator">
				@csrf {{ method_field('POST') }}
				
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times; </span></button>
					<h4 class="modal-title"></h4>
				</div>

				<div class="modal-body">
					<input type="hidden" id="id" name="id">

					<div class="form-group row">
						<label for="nama" class="col-md-2 col-md-offset-1 control-label">Nama User</label>
						<div class="col-md-6">
							<input type="text" name="nama" id="nama" class="form-control" required autofocus>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group row">
						<label for="email" class="col-md-2 col-md-offset-1 control-label">Email</label>
						<div class="col-md-6">
							<input type="text" name="email" id="email" class="form-control" required>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group row">
						<label for="password" class="col-md-2 col-md-offset-1 control-label">Password</label>
						<div class="col-md-6">
							<input type="text" name="password" id="password" class="form-control" required>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group row">
						<label for="password1" class="col-md-2 col-md-offset-1 control-label">Ulang Password</label>
						<div class="col-md-6">
							<input type="text" name="password1" id="password1" class="form-control" required data-match="#password">
							<span class="help-block with-errors"></span>
						</div>
					</div>

				</div>

				<div class="modal-footer">
					<button type="submit" class="btn btn-sm btn-flat btn-primary btn-save"><i class="fa fa-floppy-o"></i>  Simpan</button>
					<button type="button" class="btn btn-sm btn-flat btn-warning" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> Batal</button>
				</div>
			</form>
		</div>
	</div>
</div>

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title')
	Daftar User
@endsection

@section('breadcrumb')
	@parent
	<li>User</li>
@endsection

@section('content')
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
			    <div class="box-header with-border">
			        <a onclick="addForm()" class="btn btn-success btn-xs btn-flat"><i class="fa fa-plus-circle"></i> Tambah</a>
			    </div>
			
			    <div class="box-body" style="overflow: auto;">
			        <table class="table table-striped table-bordered">
			            <thead>
			                <th width="30">No</th>
			                <th>Nama User</th>
			                <th>Email</th>
			                <th width="100">Aksi</th>
			            </thead>
			            <tbody></tbody>
			        </table>
			    </div>
			</div>
		</div>
	</div>
	@include('user.form')
@endsection

@section('script')
	<script>
		var table, save_method;
	$(function() {
		table = $('.table').DataTable({
			'processing' : true,
			'autoWidth' : false,
			'ajax' : {
				'url' : '{{ route('user.data') }}',
				'type' : 'GET'
			}
		});
	})

		$(function() {
			$('#modal-form').validator().on('submit', function(e) {
				if(!e.preventDefault()) {
					var id = $('#id').val();
					
					if(save_method == 'add') url = '{{ route("user.store") }}';
					else url = 'user/' + id;

					$.ajax({
						url : url,
						type : 'POST',
						data : $('#modal-form form').serialize(),
						success : function(data) {
							$('#modal-form').modal('hide');
							table.ajax.reload();
						}
					})

					return false;
				}
			})
		})

		function addForm() {
			save_method = 'add';
			$('#modal-form').modal('show');
			$('input[name=_method]').val('POST');
			$('#modal-form form')[0].reset();
			$('.modal-title').text('Tambah User');
			$('#password, #password1').attr('required', true);
		}

		function editForm(id) {
			save_method = 'edit';
			$('input[name=_method]').val('PATCH');
			$('#modal-form form')[0].reset();

			$.ajax({
				url : 'user/' + id + '/edit',
				type : 'GET',
				dataType : 'JSON',
				success : function(data) {
					$('#modal-form').modal('show');
					$('.modal-title').text('Edit User');

					$('#id').val(data.id);
					$('#nama').val(data.name);
					$('#email').val(data.email);
					$('#password, #password1').removeAttr('required');
				}, 
				error : function() {
					alert('Tidak dapat menampilkan data');
				}
			})
		}

		function deleteData(id) {
			if(confirm('Apakah yakin data akan dihapus?')) {
				$.ajax({
					url : 'user/' + id,
					type : 'POST',
					data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
					success : function(data) {
						table.ajax.reload();
					},
					error : function() {
						alert('Tidak dapat menghapus data!');
					}
				})
			}
		}
	</script>
@endsection

resources/views/user/profil.blade.php
@extends('layouts.app')

@section('title')
	Edit Profil
@endsection

@section('breadcrumb')
	@parent
	<li>Edit Profil</li>
@endsection

@section('content')
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<form class="form fom-horizontal" method="post" data-toggle="validator" enctype="multipart/form-data">
				@csrf {{ method_field('PATCH') }}
				<div class="box-body" style="padding-top: 1em;">
					<div class="alert alert-info" role="alert" style="display: none;">
					    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					    Perubahan berhasil disimpan
					</div>

					<div class="form-group row">
					    <label for="nama" class="col-sm-2 control-label">Nama</label>
					    <div class="col-sm-6">
					    	<input type="text" name="nama" id="nama" class="form-control" required>
					    </div>
					</div>
					
					<div class="form-group row">
					    <label for="foto" class="col-sm-2 control-label">Foto</label>
					    <div class="col-sm-4">
					    	<input type="file" name="foto" id="foto" class="form-control">
					    	<br>
					    	<div class="tampil-foto">
					    		<img src="{{ asset('public/images/'. Auth::user()->foto) }}" width="200"style="border: 1px solid #ccc; box-shadow: 0 0 1px rgba(0,0,0,.25);">
					    	</div>
					    </div>
					</div>
					
					<div class="form-group row">
					    <label for="passwordlama" class="col-sm-2 control-label">Password Lama</label>
					    <div class="col-sm-6">
					    	<input type="password" name="passwordlama" id="passwordlama" class="form-control">
					    </div>
					</div>
					
					<div class="form-group row">
						<label for="password" class="col-sm-2 control-label">Password</label>
						<div class="col-sm-6">
							<input type="password" name="password" id="password" class="form-control">
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group row">
						<label for="password1" class="col-md-2 control-label">Ulang Password</label>
						<div class="col-md-6">
							<input type="password" name="password1" id="password1" class="form-control" data-match="#password">
							<span class="help-block with-errors"></span>
						</div>
					</div>
				</div>
				<div class="box-footer">
					<button class="btn btn-sm btn-flat btn-primary pull-right"><i class="fa fa-floppy-o"></i>  Simpan Perubahan</button>
				</div>
			</form>			    
			</div>
		</div>
	</div>
@endsection

@section('script')
<script>
	$(function() {
		// 1. saat password lama diubah
		$('#passwordlama').keyup(function() {
			if($(this).val() != '') $('#password, #password1').attr('required', true);
			else $('#password, #password1').attr('required', false);
		})

		$('.form').validator().on('submit', function(e) {
			if(!e.isDefaultPrevented()) {
				// upload file via ajax
				$.ajax({
					url : '{{ route('profil.update', Auth::user()->id) }}',
					type : 'POST',
					data : new FormData($('.form') [0]),
					dataType : 'JSON',
					async : false,
					processData : false,
					contentType : false,
					success : function(data) {
						// tampilakn pesan jika msg=error
						if(data.msg == 'error') {
							alert('Password lama salah!');
							$('#passwordlama').focus().select();
						} else {
							d = new Date();
							$('.alert').css('display', 'block').delay(2000).fadeOut();

							// update foto user
							$('.tampil-foto img, #user-sidebar, .user-image, .user-header img').attr('src', data.url+'?'+d.getTime());
							$('#name-navbar, #name-dropdown-menu, #name-sidebar').text(data.name);
						}

						// reset
						$('#passwordlama, #password, #password1, #foto, #nama').val('')
					},
					error : function() {
						alert('Tidak dapat menyimpan data!');
					}
				});
				return false;
			}
		})
	})
</script>
@endsection